version: '3.1'
    
services:
 db:
  image: mysql:5.5.62
  container_name: database
  restart: always
  volumes:
   - ${PWD}/mysql/data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=testcgc
   - MYSQL_PASSWORD=
   - MYSQL_DATABASE=testcgc
   - MYSQL_USER=testcgc

 pma:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  links:
   - db
  ports:
   - "8998:80"
   
 reverseproxy:
  image: nginx:alpine
  container_name: reverseproxy
  restart: always
  volumes:
   - ${PWD}/nginx.conf:/etc/nginx/nginx.conf 
   - ${PWD}/site:/etc/nginx/site 
   - ${PWD}/ssl:/opt/ssl 

  links:
   - pma
  ports:
   - "443:443"
   - "80:80"
   

   
